package CAPA_PRESENTACION; // Declaración del paquete donde se encuentra esta clase

import CAPA_LOGICA_NOTAS.DatoNotas; // Importar la clase DatoNotas del paquete CAPA_LOGICA_NOTAS
import java.awt.event.MouseEvent; // Importar la clase MouseEvent para manejar eventos del ratón
import java.util.ArrayList; // Importar la clase ArrayList para manejar listas
import javax.swing.*; // Importar las clases del paquete javax.swing
import javax.swing.table.DefaultTableModel; // Importar la clase DefaultTableModel para manejar tablas

// Declaración de la clase FormularioNotas que extiende de JFrame (interfaz gráfica)
public class FormularioNotas extends javax.swing.JFrame {

    // Constructor de la clase
    public FormularioNotas() {
        initComponents(); // Inicializar los componentes de la interfaz gráfica
        this.setSize(1100,500); // Establecer el tamaño de la ventana
        ListarArticulos(); // Llamar al método para listar los artículos en la tabla #1
        ListarArticulos2(); // Llamar al método para listar los artículos en la tabla #2
        JBTagregar.setEnabled(false); // Deshabilitar un botón llamado JBTagregar
        JBTagregar2.setEnabled(false); // Deshabilitar otro botón llamado JBTagregar2

        // Agregar un MouseListener a la tabla #1 para manejar eventos del ratón
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1Mousepressed(evt);
            }
        });

        // Agregar un MouseListener a la tabla #2 para manejar eventos del ratón
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2Mousepressed(evt);
            }
        });
    }

    // Método para listar los artículos en la tabla #1
    public void ListarArticulos(){
        DefaultTableModel tabla = new DefaultTableModel();
        DatoNotas objart = new DatoNotas();
        ArrayList<DatoNotas> lista2 = new ArrayList();
        lista2 = objart.ListaDatosBasicos();
        tabla.addColumn("Codigo");
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Correo");
        tabla.addColumn("numero");
        tabla.addColumn("Semestre");
        tabla.setRowCount(lista2.size());
        int i = 0;
        for (DatoNotas x : lista2) {
            tabla.setValueAt(x.getCodigo(), i, 0);
            tabla.setValueAt(x.getId(), i, 1);
            tabla.setValueAt(x.getNombre(), i, 2);
            tabla.setValueAt(x.getCorreo(), i, 3);
            tabla.setValueAt(x.getNum(), i, 4);
            tabla.setValueAt(x.getSemestre(), i, 5);
            i++;
        }
        this.jTable1.setModel(tabla); // Establecer el modelo de tabla en jTable1
    }

    // Método para listar los artículos en la tabla #2
    public void ListarArticulos2() {
        DefaultTableModel tabla2 = new DefaultTableModel();
        DatoNotas objart = new DatoNotas();
        ArrayList<DatoNotas> lista3 = new ArrayList();
        lista3 = objart.Listacalificaiones();
        tabla2.addColumn("Codigo");
        tabla2.addColumn("Quiz");
        tabla2.addColumn("Talleres");
        tabla2.addColumn("Parcial");
        tabla2.setRowCount(lista3.size());
        int i = 0;
        for (DatoNotas x : lista3) {
            tabla2.setValueAt(x.getCodigo(), i, 0);
            tabla2.setValueAt(x.getQuiz(), i, 1);
            tabla2.setValueAt(x.getTalleres(), i, 2);
            tabla2.setValueAt(x.getParcial(), i, 3);
            i++;
        }
        this.jTable2.setModel(tabla2); // Establecer el modelo de tabla en jTable2
    }

    // Método para limpiar los campos de texto
    public void LimpiarCajasTexto(){
        this.txtid.setText("");
        this.txtcodigo2.setText("");
        this.txtcodigo.setText("");
        this.txtcorreo.setText("");
        this.txtcodigo.setText("");
        this.txtnombre.setText("");
        this.txtnumero.setText("");
        this.txtparcial.setText("");
        this.txtquiz.setText("");
        this.txtsemestre.setText("");
        this.txttalleres.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtsemestre = new javax.swing.JTextField();
        txtquiz = new javax.swing.JTextField();
        txttalleres = new javax.swing.JTextField();
        txtparcial = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JBTagregar = new javax.swing.JButton();
        JBTmodificar = new javax.swing.JButton();
        JBTeliminar = new javax.swing.JButton();
        JBTnuevo = new javax.swing.JButton();
        JBTsalir = new javax.swing.JButton();
        JBTagregar2 = new javax.swing.JButton();
        JBTmodificar2 = new javax.swing.JButton();
        JBTeliminar2 = new javax.swing.JButton();
        JBTnuevo2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtcodigo2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Identificación del estudiante:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Correo:");

        jLabel4.setText("Numero de celular:");

        jLabel5.setText("Semestre:");

        jLabel6.setText("Quiz:");

        jLabel7.setText("Talleres:");

        jLabel8.setText("Parcial:");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });

        txtnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        JBTagregar.setText("Agregar Estudiante:");
        JBTagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTagregarActionPerformed(evt);
            }
        });

        JBTmodificar.setText("Modificar datos del estudiante:");
        JBTmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTmodificarActionPerformed(evt);
            }
        });

        JBTeliminar.setText("Eliminar Estudiante:");
        JBTeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTeliminarActionPerformed(evt);
            }
        });

        JBTnuevo.setText("Nuevo:");
        JBTnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnuevoActionPerformed(evt);
            }
        });

        JBTsalir.setText("Salir:");
        JBTsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTsalirActionPerformed(evt);
            }
        });

        JBTagregar2.setText("Agregar Notas:");
        JBTagregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTagregar2ActionPerformed(evt);
            }
        });

        JBTmodificar2.setText("Modificar Notas:");
        JBTmodificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTmodificar2ActionPerformed(evt);
            }
        });

        JBTeliminar2.setText("Eliminar notas:");
        JBTeliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTeliminar2ActionPerformed(evt);
            }
        });

        JBTnuevo2.setText("Nuevo:");
        JBTnuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnuevo2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Codigo:");

        jLabel10.setText("Codigo:");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("REGISTRO DE NOTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(JBTsalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTnuevo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBTagregar2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtparcial, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTnuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBTagregar))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBTmodificar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBTeliminar2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtquiz, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txttalleres, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(JBTmodificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(JBTeliminar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTnuevo)
                            .addComponent(JBTagregar))
                        .addGap(18, 18, 18)
                        .addComponent(JBTmodificar)
                        .addGap(12, 12, 12)
                        .addComponent(JBTeliminar)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtquiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txttalleres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtparcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBTnuevo2)
                            .addComponent(JBTagregar2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTmodificar2)
                    .addComponent(JBTeliminar2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBTsalir)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroActionPerformed
//Boton para salir del programa
    private void JBTsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTsalirActionPerformed
        int r =JOptionPane.showConfirmDialog(null,"Esta seguro?");
        if(r ==0){
            System.exit(0);
        }
    }//GEN-LAST:event_JBTsalirActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed
//Boton para Agregar nuevas notas 
    private void JBTnuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnuevo2ActionPerformed
        LimpiarCajasTexto();
        JBTagregar2.setEnabled(true);
    }//GEN-LAST:event_JBTnuevo2ActionPerformed
//Boton para eliminar notas
    private void JBTeliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTeliminar2ActionPerformed

    // Obtener los valores de los campos de texto
    String codigo = this.txtquiz.getText();
    String codigo1 = this.txttalleres.getText();
    String codigo2 = this.txtparcial.getText();
    String codigo3 = this.txtcodigo2.getText();

    // Comprobar si alguno de los campos está vacío
    if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor, seleccione notas para Eliminar.");
        return; // Terminar el método si los campos están vacíos
    }

    // Crear una instancia de la clase DatoNotas
    DatoNotas objart = new DatoNotas();

    // Mostrar un cuadro de diálogo de confirmación para eliminar notas
    int Res = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar las notas del estudiante: " + this.txtcodigo2.getText() + "?");
    if (Res == 0) { // Si el usuario confirma la eliminación
        // Establecer el código de las notas a eliminar
        objart.setCodigo(Integer.parseInt(this.txtcodigo2.getText()));

        // Mostrar un mensaje con el resultado de la eliminación y actualizar la tabla
        JOptionPane.showMessageDialog(null, objart.EliminarCalificaciones());
        ListarArticulos2();
        JOptionPane.showMessageDialog(null, "Notas Eliminadas");

        // Limpiar los campos de texto después de la eliminación
        this.LimpiarCajasTexto();
    }

    }//GEN-LAST:event_JBTeliminar2ActionPerformed
//Boton para agregar en la tabla 1
    private void JBTagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTagregarActionPerformed
// Obtener los valores de los campos de texto
        String codigo = this.txtcodigo.getText();
        String codigo1 = this.txtnombre.getText();
        String codigo2 = this.txtcorreo.getText();
        String codigo3 = this.txtnumero.getText();
        String codigo4 = this.txtsemestre.getText();
        String codigo5 = this.txtid.getText();

// Comprobar si alguno de los campos está vacío
        if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty() || codigo4.isEmpty() || codigo5.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene los espacios para Agregar un estudiante.");
            return; // Terminar el método si los campos están vacíos
        }

// Crear una instancia de la clase DatoNotas
        DatoNotas objart = new DatoNotas();

// Establecer los valores de los campos en la instancia objart
        objart.setCodigo(Integer.parseInt(this.txtcodigo.getText()));
        objart.setId(Integer.parseInt(this.txtid.getText()));
        objart.setNombre(this.txtnombre.getText());
        objart.setCorreo(this.txtcorreo.getText());
        objart.setNum(this.txtnumero.getText());
        objart.setSemestre(this.txtsemestre.getText());

// Mostrar un mensaje con el resultado de la inserción de datos
        JOptionPane.showMessageDialog(null, objart.GrabarDatosBasicos());

// Actualizar la tabla de estudiantes
        ListarArticulos();

    }//GEN-LAST:event_JBTagregarActionPerformed
//Boton para agregar en la tabla 2
    private void JBTagregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTagregar2ActionPerformed
// Obtener los valores de los campos de texto y eliminar posibles espacios en blanco al principio y al final
        String codigo = this.txtquiz.getText().trim();
        String codigo1 = this.txttalleres.getText().trim();
        String codigo3 = this.txtcodigo2.getText().trim();
        String codigo2 = this.txtparcial.getText().trim();

// Comprobar si alguno de los campos está vacío
        if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene los espacios para Agregar notas.");
            return; // Terminar el método si los campos están vacíos
        }

// Crear una instancia de la clase DatoNotas
        DatoNotas objart = new DatoNotas();

// Establecer los valores de los campos en la instancia objart
        objart.setCodigo(Integer.parseInt(this.txtcodigo2.getText()));
        objart.setQuiz(Float.parseFloat(this.txtquiz.getText()));
        objart.setTalleres(Float.parseFloat(this.txttalleres.getText()));
        objart.setParcial(Float.parseFloat(this.txtparcial.getText()));

// Mostrar un mensaje con el resultado de la inserción de calificaciones
        JOptionPane.showMessageDialog(null, objart.GrabarCalificaciones());

// Actualizar la tabla de calificaciones
        ListarArticulos2();

    }//GEN-LAST:event_JBTagregar2ActionPerformed
//Boton para Modificar datos del estudiante
    private void JBTmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTmodificarActionPerformed
// Obtener los valores de los campos de texto
        String codigo = this.txtcodigo.getText();
        String codigo1 = this.txtnombre.getText();
        String codigo2 = this.txtcorreo.getText();
        String codigo3 = this.txtnumero.getText();
        String codigo4 = this.txtsemestre.getText();
        String codigo5 = this.txtid.getText();

// Comprobar si alguno de los campos está vacío
        if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty() || codigo4.isEmpty() || codigo5.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un estudiante para Modificar.");
            return; // Terminar el método si los campos están vacíos
        }

// Crear una instancia de la clase DatoNotas
        DatoNotas objart = new DatoNotas();

// Establecer los valores de los campos en la instancia objart
        objart.setId(Integer.parseInt(this.txtid.getText()));
        objart.setCodigo(Integer.parseInt(this.txtcodigo.getText()));
        objart.setNombre(this.txtnombre.getText());
        objart.setCorreo(this.txtcorreo.getText());
        objart.setNum(this.txtnumero.getText());
        objart.setSemestre(this.txtsemestre.getText());

// Mostrar un mensaje con el resultado de la edición de datos
        JOptionPane.showMessageDialog(null, objart.EditarDatosBasicos());

// Actualizar la tabla de estudiantes
        ListarArticulos();

    }//GEN-LAST:event_JBTmodificarActionPerformed
//Boton para Modificar notas del estudiante
    private void JBTmodificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTmodificar2ActionPerformed
// Obtener los valores de los campos de texto y eliminar espacios en blanco
        String codigo = this.txtquiz.getText().trim();
        String codigo1 = this.txttalleres.getText().trim();
        String codigo2 = this.txtparcial.getText().trim();
        String codigo3 = this.txtcodigo2.getText().trim();

// Comprobar si alguno de los campos de notas está vacío
        if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione notas para Modificar.");
            return; // Terminar el método si los campos de notas están vacíos
        }

// Convertir los valores de los campos a tipos numéricos
        int codigoValor = Integer.parseInt(codigo3);
        float quizValor = Float.parseFloat(codigo);
        float talleresValor = Float.parseFloat(codigo1);
        float parcialValor = Float.parseFloat(codigo2);

// Crear una instancia de la clase DatoNotas
        DatoNotas objart = new DatoNotas();

// Establecer los valores de las notas en la instancia objart
        objart.setCodigo(codigoValor);
        objart.setQuiz(quizValor);
        objart.setTalleres(talleresValor);
        objart.setParcial(parcialValor);

// Mostrar un mensaje con el resultado de la edición de notas
        JOptionPane.showMessageDialog(null, objart.EditarCalificaciones());

// Actualizar la tabla de notas
        ListarArticulos2();

    }//GEN-LAST:event_JBTmodificar2ActionPerformed
//Boton para eliminar estudiante
    private void JBTeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTeliminarActionPerformed
// Obtener los valores de los campos de texto
        String codigo = this.txtcodigo.getText();
        String codigo1 = this.txtnombre.getText();
        String codigo2 = this.txtcorreo.getText();
        String codigo3 = this.txtnumero.getText();
        String codigo4 = this.txtsemestre.getText();
        String codigo5 = this.txtid.getText();

// Comprobar si alguno de los campos de datos está vacío
        if (codigo.isEmpty() || codigo1.isEmpty() || codigo2.isEmpty() || codigo3.isEmpty() || codigo4.isEmpty() || codigo5.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un estudiante para Eliminar.");
            return; // Terminar el método si algún campo de datos está vacío
        }

// Crear una instancia de la clase DatoNotas
        DatoNotas objart = new DatoNotas();

// Mostrar un cuadro de diálogo de confirmación para eliminar al estudiante
        int Res = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el estudiante: " + this.txtid.getText() + "?");
        if (Res == 0) { // Si el usuario confirma la eliminación
            objart.setId(Integer.parseInt(this.txtid.getText())); // Establecer el ID del estudiante en la instancia
            JOptionPane.showMessageDialog(null, objart.EliminarDatosBasicos()); // Eliminar los datos básicos del estudiante
            ListarArticulos(); // Actualizar la tabla de estudiantes
            JOptionPane.showMessageDialog(null, "Estudiante Eliminado"); // Mostrar un mensaje de confirmación
            this.LimpiarCajasTexto(); // Limpiar los campos de texto
        }

    }//GEN-LAST:event_JBTeliminarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

//Boton para crear un nuevo estudiante 
    private void JBTnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnuevoActionPerformed
        LimpiarCajasTexto();
        JBTagregar.setEnabled(true);
    }//GEN-LAST:event_JBTnuevoActionPerformed
//TABLAS
// Método para manejar el evento de clic en la tabla1
    private void jTable1Mousepressed(java.awt.event.MouseEvent evt) {
        int rec = this.jTable1.getSelectedRow(); // Obtener la fila seleccionada en la tabla1
        // Llenar los campos de texto con los valores de la fila seleccionada
        this.txtcodigo.setText(jTable1.getValueAt(rec, 0).toString());
        this.txtid.setText(jTable1.getValueAt(rec, 1).toString());
        this.txtnombre.setText(jTable1.getValueAt(rec, 2).toString());
        this.txtcorreo.setText(jTable1.getValueAt(rec, 3).toString());
        this.txtnumero.setText(jTable1.getValueAt(rec, 4).toString());
        this.txtsemestre.setText(jTable1.getValueAt(rec, 5).toString());
    }

// Método para manejar el evento de clic en la tabla2
    private void jTable2Mousepressed(java.awt.event.MouseEvent evt) {
        int rec = this.jTable2.getSelectedRow(); // Obtener la fila seleccionada en la tabla2
        // Llenar los campos de texto con los valores de la fila seleccionada
        this.txtcodigo2.setText(jTable2.getValueAt(rec, 0).toString());
        this.txtquiz.setText(jTable2.getValueAt(rec, 1).toString());
        this.txttalleres.setText(jTable2.getValueAt(rec, 2).toString());
        this.txtparcial.setText(jTable2.getValueAt(rec, 3).toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTagregar;
    private javax.swing.JButton JBTagregar2;
    private javax.swing.JButton JBTeliminar;
    private javax.swing.JButton JBTeliminar2;
    private javax.swing.JButton JBTmodificar;
    private javax.swing.JButton JBTmodificar2;
    private javax.swing.JButton JBTnuevo;
    private javax.swing.JButton JBTnuevo2;
    private javax.swing.JButton JBTsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigo2;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtparcial;
    private javax.swing.JTextField txtquiz;
    private javax.swing.JTextField txtsemestre;
    private javax.swing.JTextField txttalleres;
    // End of variables declaration//GEN-END:variables
}
